name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.1.0
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  uuid: ^4.5.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^17.0.0
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  material_symbols_icons: ^4.2805.1
  mobile_scanner: ^7.1.3
  qr_flutter: ^4.1.0
  roggle: ^0.4.2+1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  go_router_builder: ^4.1.1
  json_serializable: ^6.9.4
  pedantic_mono: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/launcher/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Thin.otf
          weight: 100
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Black.otf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
